"""Add workspace models

Revision ID: 625d986d4691
Revises: 0002
Create Date: 2026-04-03 17:19:17.824634
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '625d986d4691'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_index(op.f('ix_mia_projects_tenant_id'), 'projects', ['tenant_id'], unique=False, schema='mia')
    op.create_table('subprojects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['mia.agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['mia.projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_index(op.f('ix_mia_subprojects_tenant_id'), 'subprojects', ['tenant_id'], unique=False, schema='mia')
    op.create_table('agent_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subproject_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subproject_id'], ['mia.subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_index(op.f('ix_mia_agent_executions_tenant_id'), 'agent_executions', ['tenant_id'], unique=False, schema='mia')
    op.create_table('agent_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['mia.agent_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_table('agent_artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['mia.agent_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table('agent_artifacts', schema='mia')
    op.drop_table('agent_actions', schema='mia')
    op.drop_index(op.f('ix_mia_agent_executions_tenant_id'), table_name='agent_executions', schema='mia')
    op.drop_table('agent_executions', schema='mia')
    op.drop_index(op.f('ix_mia_subprojects_tenant_id'), table_name='subprojects', schema='mia')
    op.drop_table('subprojects', schema='mia')
    op.drop_index(op.f('ix_mia_projects_tenant_id'), table_name='projects', schema='mia')
    op.drop_table('projects', schema='mia')
    # ### end Alembic commands ###
