"""Add chat models with metadata injection

Revision ID: 77b6ac538494
Revises: 3cf4520073e1
Create Date: 2026-04-03 21:50:48.359284
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '77b6ac538494'
down_revision: Union[str, None] = '3cf4520073e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_metadata_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['mia.agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_index(op.f('ix_mia_chat_metadata_templates_tenant_id'), 'chat_metadata_templates', ['tenant_id'], unique=False, schema='mia')
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('subproject_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('session_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['mia.agents.id'], ),
    sa.ForeignKeyConstraint(['subproject_id'], ['mia.subprojects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    op.create_index(op.f('ix_mia_chat_sessions_session_code'), 'chat_sessions', ['session_code'], unique=True, schema='mia')
    op.create_index(op.f('ix_mia_chat_sessions_tenant_id'), 'chat_sessions', ['tenant_id'], unique=False, schema='mia')
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('injected_metadata', sa.JSON(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['mia.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='mia'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages', schema='mia')
    op.drop_index(op.f('ix_mia_chat_sessions_tenant_id'), table_name='chat_sessions', schema='mia')
    op.drop_index(op.f('ix_mia_chat_sessions_session_code'), table_name='chat_sessions', schema='mia')
    op.drop_table('chat_sessions', schema='mia')
    op.drop_index(op.f('ix_mia_chat_metadata_templates_tenant_id'), table_name='chat_metadata_templates', schema='mia')
    op.drop_table('chat_metadata_templates', schema='mia')
    # ### end Alembic commands ###
